apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: app-prod
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9zaGVlbGFtc2FpNV9kYl91c2VyOnNhaSU0MDEyM0BjbHVzdGVyMC5xOHVpbTB4Lm1vbmdvZGIubmV0L2Nhci1yZW50YWw=
  JWT_SECRET: c2VjcmV0Y29kZQ==
  IMAGEKIT_PUBLIC_KEY: cHVibGljX0xOSkVxeUZxM1BmL3VaOG5rcjRLWVBjbnRlaw==
  IMAGEKIT_PRIVATE_KEY: cHJpdmF0ZV80TVBJTElOS0NoR1pwV1lrVjZEdFNLS1VhNWIzZw==
  IMAGEKIT_URL_ENDPOINT: aHR0cHM6Ly9pay5pbWFnZWtpdC5pby9ibDNlbHh5OGc=
